### ISSUE TITLE
Adress conflict on bridge network - 192.168.0.0/24 is very common.

### ISSUE THREAD

**Issue by AsbjornOlling** [dtu-ese/os-challenge-common#1]
I get an address conflict when I run `$ vagrant up`, because my home LAN is also on 192.168.0.0/24.

Changing the adresses to a different subnet in `Vagrantfile` and `run-client.sh` solves the problem - but I imagine a lot of other people will also have this issue. 

I suggest changing to a less common subnet, to avoid conflicts.
I would do a pull request, but it seems overkill for so small a change.

**Comment by fontikos** [comment]
Good suggestion, thanks. I'll update it one of these days.

**Comment by fontikos** [comment]
Subnet changed to 192.168.101.0/24.
